name: Build Linux

on:
 push:
   branches: [ main, op2_llvm12 ]
 workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      PYTHON: '3.9'
      CONDA_ENV: 'cienv'
      RUN_FLAKE8: 'no'
      WHEEL: 'yes'

    steps:

      - uses: actions/checkout@v3

      - name: Before Install
        run: |
          if [ "$(uname)" == "Linux" ] && [[ "$CONDA_SUBDIR" == "linux-32" || "$BITS32" == "yes" ]]; then sudo apt-get install -y libc6-dev-i386; fi
          echo "Installing Miniconda"
          buildscripts/incremental/install_miniconda.sh
          export PATH=$HOME/miniconda3/bin:$PATH
          echo "Setting up Conda environment"
          buildscripts/incremental/setup_conda_environment.sh

      - name: Build
        run: |
          export PATH=$HOME/miniconda3/bin:$PATH
          buildscripts/incremental/build.sh
          
      # - name: Flake8
      #   run: |
      #     export PATH=$HOME/miniconda3/bin:$PATH
      #     conda install -y flake8
      #     echo "Running flake8 check"
      #     flake8 llvmlite
      #   if: $RUN_FLAKE8 == 'yes'

      - name: Test
        run: |
          export PATH=$HOME/miniconda3/bin:$PATH
          buildscripts/incremental/test.sh


