name: Build Windows

on:
 push:
   branches: [ main, op2_llvm12 ]
 workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    env:
      PYTHON: '3.9'
      CONDA_ENV: cienv
      GITHUB_WORKSPACE: ${{ github.workspace }}

    steps:

      - uses: actions/checkout@v3
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}

            # ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            # hashFiles('etc/example-environment.yml') }}

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.9"
          activate-environment: cienv

      # - name: Install miniconda
      #   shell: powershell
      #   run: |
      #     $wc = New-Object net.webclient
      #     $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
      #     Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait

      - name: Install
        shell: cmd
        run: |
          call conda install -y -q -c numba llvmdev="11.*"

      - name: Build
        shell: cmd
        run: |
          call python %GITHUB_WORKSPACE%\setup.py build

      - name: Test
        shell: cmd
        run: |
          call python %GITHUB_WORKSPACE%\runtests.py -v
